### PR TITLE
Update dependency after Package Control update

### LINKED ISSUE #12: Package names in dependencies.json
Package names in dependencies.json should point to official pypi package names, not their PEP491 escaped filesystem representation.

```json
{
  "*": {
    ">=4000": [
      "tree-sitter",
      "tree-sitter-languages"
    ]
  }
}
```

Package Control 4.0.3 now correctly handles package/distribution names according to PEP491.

see: https://github.com/wbond/package_control/issues/1667

### PR DESCRIPTION
**Pull request by kaste**
Ref: wbond/package_control#1667
Fixes #12

### CODE REVIEW

**Comment by kaste** [comment]
@kylebebak This is a hotfix!  Without it Sublime/PC will be in a "please restart" loop.  (But you don't have to restart and everything will work.  So just click "cancel".)

**Comment by kylebebak** [comment]
Thanks @kaste and @deathaxe for catching this and fixing it so quickly!

**Comment by kaste** [comment]
Yeah, don't forget to release/tag this one!

**Comment by kylebebak** [comment]
I totally forgot to do this @kaste , thank you for the reminder!

Here's the release: https://github.com/sublime-treesitter/TreeSitter/releases/tag/1.5.2

**Pull request merged**
